root: true
env:
  browser: true
  jest: true
extends:
  ['standard-with-typescript', 'plugin:react/recommended', plugin:react/jsx-runtime, 'plugin:prettier/recommended']
parser: '@typescript-eslint/parser'
parserOptions:
  project: ['tsconfig.json', 'packages/*/tsconfig.json']
settings:
  react:
    version: detect
ignorePatterns: ['dist', 'build', 'node_modules']